apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpd-get-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpd-get-ms
  template:
    metadata:
      labels:
        app: bpd-get-ms
    spec:
      containers:
        - name: bpd-get-container
          image: bpd-get-ms
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: bpd-crud-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bpd-crud-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: bpd-crud-secrets
                  key: JWT_EXPIRATION
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: bpd-crud-secrets
                  key: API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: bpd-crud-secrets
                  key: API_SECRET
            - name: INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bpd-crud-secrets
                  key: INTERNAL_API_KEY
            - name: INTERNAL_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: bpd-crud-secrets
                  key: INTERNAL_API_SECRET
            - name: CRUD_MS_URL
              value: "http://bpd-crud-ms:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: bpd-get-ms
spec:
  selector:
    app: bpd-get-ms
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
