apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpd-crud-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpd-crud-ms
  template:
    metadata:
      labels:
        app: bpd-crud-ms
    spec:
      containers:
        - name: bpd-crud-container
          image: bpd-crud-ms
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: bpd-crud-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bpd-crud-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: bpd-crud-secrets
                  key: JWT_EXPIRATION
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: bpd-crud-secrets
                  key: API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: bpd-crud-secrets
                  key: API_SECRET
            - name: INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bpd-crud-secrets
                  key: INTERNAL_API_KEY
            - name: INTERNAL_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: bpd-crud-secrets
                  key: INTERNAL_API_SECRET
            - name: BPD_GET_MS_URL
              value: "http://bpd-get-ms:3001"
---
apiVersion: v1
kind: Service
metadata:
  name: bpd-crud-ms
spec:
  selector:
    app: bpd-crud-ms
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
