openapi: 3.0.0
info:
  title: BPD CRUD Microservice
  version: 1.0.0
  description: API for creating, updating, and deleting user profiles
servers:
  - url: http://localhost:3000
paths:
  /api/create-profile:
    post:
      summary: Create a user profile
      security:
        - bearerAuth: []
        - apiKeyAuth: []
        - apiSecretAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                lastName:
                  type: string
                cellphone:
                  type: string
                email:
                  type: string
                address:
                  type: string
      responses:
        '201':
          description: Profile created
  /api/delete-profile:
    delete:
      summary: Delete own user profile
      security:
        - bearerAuth: []
        - apiKeyAuth: []
        - apiSecretAuth: []
      responses:
        '200':
          description: Profile deleted
  /api/update-profile:
    put:
      summary: Update own user profile
      security:
        - bearerAuth: []
        - apiKeyAuth: []
        - apiSecretAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                lastName:
                  type: string
                cellphone:
                  type: string
                email:
                  type: string
                address:
                  type: string
      responses:
        '200':
          description: Profile updated
  /api/logs:
  get:
    summary: Get logs of the authenticated user
    description: Returns all logs (create, read, update, delete) performed by the authenticated user.
    security:
      - bearerAuth: []
      - apiKeyAuth: []
      - apiSecretAuth: []
    responses:
      '200':
        description: List of user logs
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  action:
                    type: string
                    example: created
                  timestamp:
                    type: string
                    format: date-time
                  message:
                    type: string
                    example: Profile created
      '401':
        description: Missing or invalid token
      '403':
        description: Forbidden - cannot view logs of other users
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    apiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
    apiSecretAuth:
      type: apiKey
      in: header
      name: x-api-secret